#
control_freq: 50

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

render_gui: true          # Show real-time GUI for debugging

# state always has 29 dof
isaac_joint_names_state: ['left_hip_pitch_joint', 'right_hip_pitch_joint', 'waist_yaw_joint', 'left_hip_roll_joint', 'right_hip_roll_joint', 'waist_roll_joint', 'left_hip_yaw_joint', 'right_hip_yaw_joint', 'waist_pitch_joint', 'left_knee_joint', 'right_knee_joint', 'left_shoulder_pitch_joint', 'right_shoulder_pitch_joint', 'left_ankle_pitch_joint', 'right_ankle_pitch_joint', 'left_shoulder_roll_joint', 'right_shoulder_roll_joint', 'left_ankle_roll_joint', 'right_ankle_roll_joint', 'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint', 'left_elbow_joint', 'right_elbow_joint', 'left_wrist_roll_joint', 'right_wrist_roll_joint', 'left_wrist_pitch_joint', 'right_wrist_pitch_joint', 'left_wrist_yaw_joint', 'right_wrist_yaw_joint']

# Real robot joint names
real_joint_names: [
  "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
  "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint", "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",
  "waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint",
  "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint", "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint",
  "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint", "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint"
]

# Mujoco joint names
mujoco_joint_names: [
  "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
  "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint", "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",
  "waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint",
  "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint", "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint",
  "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint", "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint"
]


kps_real: [
  # left leg
  99.09842777666113, 99.09842777666113, 40.17923847137318, 99.09842777666113, 28.50124619574858, 28.50124619574858,
  # right leg
  99.09842777666113, 99.09842777666113, 40.17923847137318, 99.09842777666113, 28.50124619574858, 28.50124619574858,
  # waist
  40.17923847137318, 28.50124619574858, 28.50124619574858,
  # left arm
  14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 8.611032447370201, 8.611032447370201,
  # right arm
  14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 8.611032447370201, 8.611032447370201,
]

kds_real: [
  # left leg
  6.3088018534966395, 6.3088018534966395, 2.5578897650279457, 6.3088018534966395, 1.814445686584846, 1.814445686584846,
  # right leg
  6.3088018534966395, 6.3088018534966395, 2.5578897650279457, 6.3088018534966395, 1.814445686584846, 1.814445686584846,
  # waist
  2.5578897650279457, 1.814445686584846, 1.814445686584846,
  # left arm
  0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.548195351665136, 0.548195351665136,
  # right arm
  0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.548195351665136, 0.548195351665136,
]

default_qpos_real: [
  -0.28, 0, 0, 0.5, -0.23, 0,         # left leg
  -0.28, 0, 0, 0.5, -0.23, 0,         # right leg
  0, 0, 0,                  # waist
  0.35, 0.16, 0, 0.87, 0, 0, 0,  # left arm
  0.35, -0.16, 0, 0.87, 0, 0, 0, # right arm
]

init_qpos_real: [
  -0.28, 0, 0, 0.5, -0.23, 0,         # left leg
  -0.28, 0, 0, 0.5, -0.23, 0,         # right leg
  0, 0, 0,                  # waist
  0.35, 0.16, 0, 0.87, 0, 0, 0,  # left arm
  0.35, -0.16, 0, 0.87, 0, 0, 0, # right arm
]
