# low latency
policy_path: "assets/ckpts/G1TRACKING-03-16_14-15_0315.2/policy.onnx"

compliance_flag_value: 1.0 # 0.0 to disable compliance, 1.0 to enable compliance
compliance_flag_threshold: 10.0 # 10.0 ~ 20.0
future_steps: [0, 1, 2, 3, 4, -1, -2, -4, -8, -12, -16] # format: [0, ...future, ...history]
motion_source: "vr"
vr_req_addr: "tcp://127.0.0.1:28701"
vr_rep_addr: "tcp://127.0.0.1:28702"
vr_ctrl_addr: "tcp://127.0.0.1:28703"
vr_low_watermark: 5 # when to request frame
vr_high_watermark: 5 # when to stop requesting frame; should be >= low_watermark
vr_chunk_frames: 1 # how many frames to request each time
vr_inflight_lifetime_steps: 0 # how many steps to wait before considering an inflight request as failed
root_linacc_history_steps: [0, 1, 2, 3, 4, 8, 12, 16, 20]
root_angvel_history_steps: [0, 1, 2, 3, 4, 8, 12, 16, 20]
projected_gravity_history_steps: [0, 1, 2, 3, 4, 8, 12, 16, 20]
joint_pos_history_steps: [0, 1, 2, 3, 4, 8, 12, 16, 20]
joint_vel_history_steps: [0, 1, 2, 3, 4, 8, 12, 16, 20]
prev_action_steps: 8
switch_tail_keep_steps: 8 # keep old ref tail on motion switch; final keep is max(this, abs(min(future_steps)))

motions:
  - name: "dance1_subject1"
    path: "assets/data/dance1_subject1.npz"
    start: 0
    end: -1
  - name: "dance2_subject1"
    path: "assets/data/dance2_subject1.npz"
    start: 0
    end: -1
  - name: "fallAndGetUp1_subject1"
    path: "assets/data/fallAndGetUp1_subject1.npz"
    start: 0
    end: -1
  - name: "fallAndGetUp2_subject2"
    path: "assets/data/fallAndGetUp2_subject2.npz"
    start: 0
    end: -1
  - name: "fight1_subject2"
    path: "assets/data/fight1_subject2.npz"
    start: 0
    end: -1
  - name: "fightAndSports1_subject1"
    path: "assets/data/fightAndSports1_subject1.npz"
    start: 0
    end: -1
  - name: "jumps1_subject1"
    path: "assets/data/jumps1_subject1.npz"
    start: 0
    end: -1
  - name: "run1_subject2"
    path: "assets/data/run1_subject2.npz"
    start: 0
    end: -1
  - name: "run2_subject1"
    path: "assets/data/run2_subject1.npz"
    start: 0
    end: -1
  - name: "sprint1_subject2"
    path: "assets/data/sprint1_subject2.npz"
    start: 0
    end: -1
  - name: "walk1_subject1"
    path: "assets/data/walk1_subject1.npz"
    start: 0
    end: -1
  - name: "walk2_subject1"
    path: "assets/data/walk2_subject1.npz"
    start: 0
    end: -1
  - name: "walk3_subject1"
    path: "assets/data/walk3_subject1.npz"
    start: 0
    end: -1
motion_clips:
  - name: "default"
    joint_pos: [-0.2800000011920929, 0.0, 0.0, 0.5, -0.23000000417232513, 0.0, -0.2800000011920929, 0.0, 0.0, 0.5, -0.23000000417232513, 0.0, 0.0, 0.0, 0.0, 0.3499999940395355, 0.1599999964237213, 0.0, 0.8700000047683716, 0.0, 0.0, 0.0, 0.3499999940395355, -0.1599999964237213, 0.0, 0.8700000047683716, 0.0, 0.0, 0.0]
    root_quat: [1., 0., 0., 0.]
    root_pos: [0.0, 0.0, 0.78]

action_clip: 10.0

action_joint_names: ['left_hip_pitch_joint', 'right_hip_pitch_joint', 'waist_yaw_joint', 'left_hip_roll_joint', 'right_hip_roll_joint', 'waist_roll_joint', 'left_hip_yaw_joint', 'right_hip_yaw_joint', 'waist_pitch_joint', 'left_knee_joint', 'right_knee_joint', 'left_shoulder_pitch_joint', 'right_shoulder_pitch_joint', 'left_ankle_pitch_joint', 'right_ankle_pitch_joint', 'left_shoulder_roll_joint', 'right_shoulder_roll_joint', 'left_ankle_roll_joint', 'right_ankle_roll_joint', 'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint', 'left_elbow_joint', 'right_elbow_joint', 'left_wrist_roll_joint', 'right_wrist_roll_joint', 'left_wrist_pitch_joint', 'right_wrist_pitch_joint', 'left_wrist_yaw_joint', 'right_wrist_yaw_joint']

action_scale: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 0.5, 0.5, 1.0, 1.0, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # AMASS model action scale

dataset_joint_names: ["left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint", "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint", "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint", "waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint", "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint", "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint", "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint", "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint"]

kps_real: [
  # left leg
  99.09842777666113, 99.09842777666113, 40.17923847137318, 99.09842777666113, 28.50124619574858, 28.50124619574858,
  # right leg
  99.09842777666113, 99.09842777666113, 40.17923847137318, 99.09842777666113, 28.50124619574858, 28.50124619574858,
  # waist
  40.17923847137318, 28.50124619574858, 28.50124619574858,
  # left arm
  14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 8.611032447370201, 8.611032447370201,
  # right arm
  14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 8.611032447370201, 8.611032447370201,
]

kds_real: [
  # left leg
  6.3088018534966395, 6.3088018534966395, 2.5578897650279457, 6.3088018534966395, 1.814445686584846, 1.814445686584846,
  # right leg
  6.3088018534966395, 6.3088018534966395, 2.5578897650279457, 6.3088018534966395, 1.814445686584846, 1.814445686584846,
  # waist
  2.5578897650279457, 1.814445686584846, 1.814445686584846,
  # left arm
  0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.548195351665136, 0.548195351665136,
  # right arm
  0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.548195351665136, 0.548195351665136,
]
